In [1]:
!git clone https://github.com/psmajethiya/Inflation-drivers-in-India.git
%cd Inflation-drivers-in-India

Cloning into 'Inflation-drivers-in-India'...
remote: Enumerating objects: 76, done.
remote: Counting objects: 100% (76/76), done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 76 (delta 19), reused 30 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (76/76), 81.44 KiB | 5.82 MiB/s, done.
Resolving deltas: 100% (19/19), done.
/content/Inflation-drivers-in-India

In [2]:
import pandas as pd

cpi = pd.read_csv("data/cpi_clean.csv")
cpi.head()

      Date    CPI   CPI_mom
0  2015-01  119.5       NaN
1  2015-02  119.7  0.167364
2  2015-03  120.2  0.417711
3  2015-04  120.7  0.415973
4  2015-05  121.6  0.745650

In [3]:
iip = pd.read_csv("data/iip_clean.csv")
iip.head()

      Date    IIP   IIP_yoy
0  2015-01  114.3  1.780944
1  2015-02  109.9  2.999063
2  2015-03  121.3  2.362869
3  2015-04  107.3  0.656660
4  2015-05  113.0  1.801802

In [8]:
fx = pd.read_csv("data/fx_clean.csv")
fx.head()

      Date       FX
0  2015-01  62.1300
1  2015-02  61.9905
2  2015-03  62.4805
3  2015-04  62.6414
4  2015-05  63.7150

In [9]:
oil = pd.read_csv("data/oil_clean.csv")
oil.head()

      Date      Oil
0  2015-01  47.7595
1  2015-02  58.0955
2  2015-03  55.8855
3  2015-04  59.5243
4  2015-05  64.0750

In [6]:
repo = pd.read_csv("data/repo_clean.csv")
repo.head()

      Date  Repo
0  2015-01  7.75
1  2015-02  7.75
2  2015-03  7.50
3  2015-04  7.50
4  2015-05  7.50

In [7]:
df = pd.read_csv("data/final_combined.csv")
df.head()

      Date  CPI_mom  Repo      Oil       FX  IIP_yoy
0  2015-02    0.167  7.75  58.0955  61.9905    2.999
1  2015-03    0.418  7.50  55.8855  62.4805    2.363
2  2015-04    0.416  7.50  59.5243  62.6414    0.657
3  2015-05    0.746  7.50  64.0750  63.7150    1.802
4  2015-06    1.151  7.25  61.4777  63.7809    1.003